"""make paper file_url nullable for drafts

Revision ID: 024677c27b7b
Revises: 93fa329c9405
Create Date: 2026-09-10 18:55:55.950956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '024677c27b7b'
down_revision: Union[str, None] = '93fa329c9405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('papers', 'track',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('papers', 'abstract',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('papers', 'file_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('papers', 'file_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('papers', 'abstract',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('papers', 'track',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
