"""add website module tables

Revision ID: 0c1abc082fb1
Revises: 4972934041f7
Create Date: 2026-09-12 22:47:53.596184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1abc082fb1'
down_revision: Union[str, None] = '4972934041f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coordination_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_department', sa.String(length=50), nullable=False),
    sa.Column('to_department', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'addressed', name='coordinationstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coordination_requests_id'), 'coordination_requests', ['id'], unique=False)
    op.create_table('digital_communications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'in_app', 'both', name='communicationchannel'), nullable=False),
    sa.Column('recipient_filter', sa.String(length=50), nullable=True),
    sa.Column('recipient_count', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'sent', 'failed', name='communicationstatus'), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digital_communications_id'), 'digital_communications', ['id'], unique=False)
    op.create_table('online_forms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'closed', name='formstatus'), nullable=False),
    sa.Column('submission_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_online_forms_id'), 'online_forms', ['id'], unique=False)
    op.create_table('website_news',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('announcement', 'news', 'update', name='newscategory'), nullable=False),
    sa.Column('publish_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('target_audience', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='pagestatus'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_news_id'), 'website_news', ['id'], unique=False)
    op.create_table('website_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='pagestatus'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('published_by', sa.UUID(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_pages_id'), 'website_pages', ['id'], unique=False)
    op.create_index(op.f('ix_website_pages_slug'), 'website_pages', ['slug'], unique=True)
    op.create_index(op.f('ix_website_pages_status'), 'website_pages', ['status'], unique=False)
    op.create_table('form_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.Enum('text', 'textarea', 'dropdown', 'checkbox', 'radio', 'date', 'file', 'number', 'email', name='formfieldtype'), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('placeholder', sa.String(length=255), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['online_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_fields_form_id'), 'form_fields', ['form_id'], unique=False)
    op.create_index(op.f('ix_form_fields_id'), 'form_fields', ['id'], unique=False)
    op.create_table('form_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['online_forms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_submissions_form_id'), 'form_submissions', ['form_id'], unique=False)
    op.create_index(op.f('ix_form_submissions_id'), 'form_submissions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_submissions_id'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_form_id'), table_name='form_submissions')
    op.drop_table('form_submissions')
    op.drop_index(op.f('ix_form_fields_id'), table_name='form_fields')
    op.drop_index(op.f('ix_form_fields_form_id'), table_name='form_fields')
    op.drop_table('form_fields')
    op.drop_index(op.f('ix_website_pages_status'), table_name='website_pages')
    op.drop_index(op.f('ix_website_pages_slug'), table_name='website_pages')
    op.drop_index(op.f('ix_website_pages_id'), table_name='website_pages')
    op.drop_table('website_pages')
    op.drop_index(op.f('ix_website_news_id'), table_name='website_news')
    op.drop_table('website_news')
    op.drop_index(op.f('ix_online_forms_id'), table_name='online_forms')
    op.drop_table('online_forms')
    op.drop_index(op.f('ix_digital_communications_id'), table_name='digital_communications')
    op.drop_table('digital_communications')
    op.drop_index(op.f('ix_coordination_requests_id'), table_name='coordination_requests')
    op.drop_table('coordination_requests')
    # ### end Alembic commands ###
