"""add abstract domain draft review

Revision ID: 19a8d4be6647
Revises: 6ead7bb6a7b8
Create Date: 2026-09-11 18:03:52.013721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19a8d4be6647'
down_revision: Union[str, None] = '6ead7bb6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('papers', 'domain',
               existing_type=postgresql.ENUM('mining', 'renewable', 'environmental', name='paperdomain'),
               type_=sa.String(length=100),
               nullable=True,
               existing_server_default=sa.text("'mining'::paperdomain"))
    op.alter_column('papers', 'review_status',
               existing_type=postgresql.ENUM('submitted', 'under_review', 'accepted', 'rejected', 'revision_needed', name='paperstatus'),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'submitted'::paperstatus"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('papers', 'review_status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('submitted', 'under_review', 'accepted', 'rejected', 'revision_needed', name='paperstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'submitted'::paperstatus"))
    op.alter_column('papers', 'domain',
               existing_type=sa.String(length=100),
               type_=postgresql.ENUM('mining', 'renewable', 'environmental', name='paperdomain'),
               nullable=False,
               existing_server_default=sa.text("'mining'::paperdomain"))
    # ### end Alembic commands ###
