"""add qr_hash department committee_member

Revision ID: 244f1cab7932
Revises: 5867a3a899df
Create Date: 2026-09-12 13:29:55.355900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '244f1cab7932'
down_revision: Union[str, None] = '5867a3a899df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_venue_tasks_assigned_to', table_name='venue_tasks')
    op.drop_index('ix_venue_tasks_category', table_name='venue_tasks')
    op.drop_index('ix_venue_tasks_id', table_name='venue_tasks')
    op.drop_index('ix_venue_tasks_status', table_name='venue_tasks')
    op.drop_table('venue_tasks')
    op.drop_index('ix_room_allocations_id', table_name='room_allocations')
    op.drop_table('room_allocations')
    op.drop_index('ix_equipment_category', table_name='equipment')
    op.drop_index('ix_equipment_id', table_name='equipment')
    op.drop_table('equipment')
    op.drop_index('ix_event_timeline_id', table_name='event_timeline')
    op.drop_table('event_timeline')
    op.drop_index('ix_venue_checklists_category', table_name='venue_checklists')
    op.drop_index('ix_venue_checklists_id', table_name='venue_checklists')
    op.drop_table('venue_checklists')
    op.add_column('users', sa.Column('qr_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('assigned_by_head', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_user_domain', table_name='users')
    op.drop_index('ix_user_role', table_name='users')
    op.create_index(op.f('ix_users_qr_hash'), 'users', ['qr_hash'], unique=True)
    op.drop_column('users', 'designation')
    op.drop_column('users', 'city')
    op.drop_column('users', 'graduation_year')
    op.drop_column('users', 'category')
    op.drop_column('users', 'experience')
    op.drop_column('users', 'education_level')
    op.drop_column('users', 'organization')
    op.drop_column('users', 'institution')
    op.drop_column('users', 'field_of_study')
    op.drop_column('users', 'student_class')
    op.drop_column('users', 'state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('student_class', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('field_of_study', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('institution', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('organization', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('education_level', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('experience', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('graduation_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('designation', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_qr_hash'), table_name='users')
    op.create_index('ix_user_role', 'users', ['role'], unique=False)
    op.create_index('ix_user_domain', 'users', ['specialized_domain'], unique=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'assigned_by_head')
    op.drop_column('users', 'department')
    op.drop_column('users', 'qr_hash')
    op.create_table('venue_checklists',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('template_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('item', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('completed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], name='venue_checklists_completed_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='venue_checklists_pkey')
    )
    op.create_index('ix_venue_checklists_id', 'venue_checklists', ['id'], unique=False)
    op.create_index('ix_venue_checklists_category', 'venue_checklists', ['category'], unique=False)
    op.create_table('event_timeline',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('venue', 'infrastructure', 'event_day', name='taskcategory'), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('assigned_to', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name='event_timeline_assigned_to_fkey'),
    sa.PrimaryKeyConstraint('id', name='event_timeline_pkey')
    )
    op.create_index('ix_event_timeline_id', 'event_timeline', ['id'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('total_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('available_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('booked_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('condition', postgresql.ENUM('excellent', 'good', 'needs_repair', 'broken', name='equipmentcondition'), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_inspected', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='equipment_pkey')
    )
    op.create_index('ix_equipment_id', 'equipment', ['id'], unique=False)
    op.create_index('ix_equipment_category', 'equipment', ['category'], unique=False)
    op.create_table('room_allocations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('room_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('room_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('floor', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('grid_position', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('allocated_to', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('session_type', postgresql.ENUM('technical', 'keynote', 'workshop', 'exhibition', 'registration', 'other', name='sessiontype'), autoincrement=False, nullable=True),
    sa.Column('time_slot', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('special_requirements', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_confirmed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='room_allocations_pkey')
    )
    op.create_index('ix_room_allocations_id', 'room_allocations', ['id'], unique=False)
    op.create_table('venue_tasks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('venue', 'infrastructure', 'event_day', name='taskcategory'), autoincrement=False, nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('not_started', 'in_progress', 'completed', 'blocked', name='taskstatus'), autoincrement=False, nullable=False),
    sa.Column('priority', postgresql.ENUM('high', 'medium', 'low', name='taskpriority'), autoincrement=False, nullable=False),
    sa.Column('assigned_to', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deadline', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name='venue_tasks_assigned_to_fkey'),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], name='venue_tasks_completed_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='venue_tasks_pkey')
    )
    op.create_index('ix_venue_tasks_status', 'venue_tasks', ['status'], unique=False)
    op.create_index('ix_venue_tasks_id', 'venue_tasks', ['id'], unique=False)
    op.create_index('ix_venue_tasks_category', 'venue_tasks', ['category'], unique=False)
    op.create_index('ix_venue_tasks_assigned_to', 'venue_tasks', ['assigned_to'], unique=False)
    # ### end Alembic commands ###
