""" add id card tables and user fields

Revision ID: 34ad51b83326
Revises: d4c0767acff5
Create Date: 2026-09-13 03:34:22.731371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34ad51b83326'
down_revision: Union[str, None] = 'd4c0767acff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('id_card_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_role', sa.String(length=50), nullable=False),
    sa.Column('template_image_path', sa.String(length=500), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_id_card_templates_id'), 'id_card_templates', ['id'], unique=False)
    op.create_index(op.f('ix_id_card_templates_target_role'), 'id_card_templates', ['target_role'], unique=False)
    op.create_table('id_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('pdf_path', sa.String(length=500), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('print_status', sa.Enum('pending', 'printed', 'collected', name='printstatus'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['id_card_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_id_cards_id'), 'id_cards', ['id'], unique=False)
    op.create_index(op.f('ix_id_cards_print_status'), 'id_cards', ['print_status'], unique=False)
    op.create_index(op.f('ix_id_cards_user_id'), 'id_cards', ['user_id'], unique=False)
    op.add_column('users', sa.Column('id_card_generated', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('photo_path', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_users_id_card_generated'), 'users', ['id_card_generated'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id_card_generated'), table_name='users')
    op.drop_column('users', 'photo_path')
    op.drop_column('users', 'id_card_generated')
    op.drop_index(op.f('ix_id_cards_user_id'), table_name='id_cards')
    op.drop_index(op.f('ix_id_cards_print_status'), table_name='id_cards')
    op.drop_index(op.f('ix_id_cards_id'), table_name='id_cards')
    op.drop_table('id_cards')
    op.drop_index(op.f('ix_id_card_templates_target_role'), table_name='id_card_templates')
    op.drop_index(op.f('ix_id_card_templates_id'), table_name='id_card_templates')
    op.drop_table('id_card_templates')
    # ### end Alembic commands ###
