"""add failed login attempts table

Revision ID: 4c34a64a947c
Revises: db012ae1a8cd
Create Date: 2026-09-13 12:09:58.990394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c34a64a947c'
down_revision: Union[str, None] = 'db012ae1a8cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contact_inquiries_email', table_name='contact_inquiries')
    op.drop_index('ix_contact_inquiries_id', table_name='contact_inquiries')
    op.drop_index('ix_contact_inquiries_status', table_name='contact_inquiries')
    op.drop_table('contact_inquiries')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_inquiries',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subject', postgresql.ENUM('general_inquiry', 'registration_support', 'paper_submission_issue', 'sponsorship_opportunities', 'technical_issue', 'other', name='inquirysubject'), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('new', 'read', 'replied', 'closed', name='inquirystatus'), autoincrement=False, nullable=False),
    sa.Column('admin_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('responded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='contact_inquiries_pkey')
    )
    op.create_index('ix_contact_inquiries_status', 'contact_inquiries', ['status'], unique=False)
    op.create_index('ix_contact_inquiries_id', 'contact_inquiries', ['id'], unique=False)
    op.create_index('ix_contact_inquiries_email', 'contact_inquiries', ['email'], unique=False)
    # ### end Alembic commands ###
