"""expand registration fields

Revision ID: 54ebe2e768d2
Revises: 720e7dced203
Create Date: 2026-09-10 16:50:42.576643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54ebe2e768d2'
down_revision: Union[str, None] = '720e7dced203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('sub_category', sa.String(), nullable=True))
    op.add_column('registrations', sa.Column('education_level', sa.String(), nullable=True))
    op.add_column('registrations', sa.Column('student_class', sa.String(), nullable=True))
    op.add_column('registrations', sa.Column('field_of_study', sa.String(), nullable=True))
    op.add_column('registrations', sa.Column('graduation_year', sa.Integer(), nullable=True))
    op.add_column('registrations', sa.Column('organization', sa.String(), nullable=True))
    op.add_column('registrations', sa.Column('designation', sa.String(), nullable=True))
    op.add_column('registrations', sa.Column('experience', sa.Integer(), nullable=True))
    op.add_column('registrations', sa.Column('state', sa.String(), nullable=True))
    op.add_column('registrations', sa.Column('city', sa.String(), nullable=True))
    op.add_column('registrations', sa.Column('paper_title', sa.String(), nullable=True))
    op.add_column('registrations', sa.Column('co_authors', sa.JSON(), nullable=True))
    op.add_column('reviews', sa.Column('submitted', sa.Boolean(), nullable=False))
    op.add_column('reviews', sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('reviews', 'scores_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('reviews', 'recommendation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'recommendation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('reviews', 'scores_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('reviews', 'assigned_at')
    op.drop_column('reviews', 'submitted')
    op.drop_column('registrations', 'co_authors')
    op.drop_column('registrations', 'paper_title')
    op.drop_column('registrations', 'city')
    op.drop_column('registrations', 'state')
    op.drop_column('registrations', 'experience')
    op.drop_column('registrations', 'designation')
    op.drop_column('registrations', 'organization')
    op.drop_column('registrations', 'graduation_year')
    op.drop_column('registrations', 'field_of_study')
    op.drop_column('registrations', 'student_class')
    op.drop_column('registrations', 'education_level')
    op.drop_column('registrations', 'sub_category')
    # ### end Alembic commands ###
