"""add volunteer scanner endpoints

Revision ID: 5867a3a899df
Revises: b001f17aea03
Create Date: 2026-09-12 12:17:40.423620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5867a3a899df'
down_revision: Union[str, None] = 'b001f17aea03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_room_allocations_id', table_name='room_allocations')
    op.drop_table('room_allocations')
    op.drop_index('ix_venue_tasks_assigned_to', table_name='venue_tasks')
    op.drop_index('ix_venue_tasks_category', table_name='venue_tasks')
    op.drop_index('ix_venue_tasks_id', table_name='venue_tasks')
    op.drop_index('ix_venue_tasks_status', table_name='venue_tasks')
    op.drop_table('venue_tasks')
    op.drop_index('ix_equipment_category', table_name='equipment')
    op.drop_index('ix_equipment_id', table_name='equipment')
    op.drop_table('equipment')
    op.drop_index('ix_event_timeline_id', table_name='event_timeline')
    op.drop_table('event_timeline')
    op.drop_index('ix_venue_checklists_category', table_name='venue_checklists')
    op.drop_index('ix_venue_checklists_id', table_name='venue_checklists')
    op.drop_table('venue_checklists')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue_checklists',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('template_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('item', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('completed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], name='venue_checklists_completed_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='venue_checklists_pkey')
    )
    op.create_index('ix_venue_checklists_id', 'venue_checklists', ['id'], unique=False)
    op.create_index('ix_venue_checklists_category', 'venue_checklists', ['category'], unique=False)
    op.create_table('event_timeline',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('venue', 'infrastructure', 'event_day', name='taskcategory'), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('assigned_to', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name='event_timeline_assigned_to_fkey'),
    sa.PrimaryKeyConstraint('id', name='event_timeline_pkey')
    )
    op.create_index('ix_event_timeline_id', 'event_timeline', ['id'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('total_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('available_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('booked_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('condition', postgresql.ENUM('excellent', 'good', 'needs_repair', 'broken', name='equipmentcondition'), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_inspected', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='equipment_pkey')
    )
    op.create_index('ix_equipment_id', 'equipment', ['id'], unique=False)
    op.create_index('ix_equipment_category', 'equipment', ['category'], unique=False)
    op.create_table('venue_tasks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('venue', 'infrastructure', 'event_day', name='taskcategory'), autoincrement=False, nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('not_started', 'in_progress', 'completed', 'blocked', name='taskstatus'), autoincrement=False, nullable=False),
    sa.Column('priority', postgresql.ENUM('high', 'medium', 'low', name='taskpriority'), autoincrement=False, nullable=False),
    sa.Column('assigned_to', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deadline', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name='venue_tasks_assigned_to_fkey'),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], name='venue_tasks_completed_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='venue_tasks_pkey')
    )
    op.create_index('ix_venue_tasks_status', 'venue_tasks', ['status'], unique=False)
    op.create_index('ix_venue_tasks_id', 'venue_tasks', ['id'], unique=False)
    op.create_index('ix_venue_tasks_category', 'venue_tasks', ['category'], unique=False)
    op.create_index('ix_venue_tasks_assigned_to', 'venue_tasks', ['assigned_to'], unique=False)
    op.create_table('room_allocations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('room_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('room_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('floor', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('grid_position', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('allocated_to', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('session_type', postgresql.ENUM('technical', 'keynote', 'workshop', 'exhibition', 'registration', 'other', name='sessiontype'), autoincrement=False, nullable=True),
    sa.Column('time_slot', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('special_requirements', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_confirmed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='room_allocations_pkey')
    )
    op.create_index('ix_room_allocations_id', 'room_allocations', ['id'], unique=False)
    # ### end Alembic commands ###
