"""remove conference_name accompanying_fee add important_dates

Revision ID: 67672afa999f
Revises: 34ad51b83326
Create Date: 2026-09-13 05:02:14.919724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67672afa999f'
down_revision: Union[str, None] = '34ad51b83326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conference_settings', sa.Column('important_dates', sa.JSON(), nullable=True))
    op.drop_column('conference_settings', 'conference_name')
    op.drop_column('conference_settings', 'accompanying_fee')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conference_settings', sa.Column('accompanying_fee', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('conference_settings', sa.Column('conference_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('conference_settings', 'important_dates')
    # ### end Alembic commands ###
