"""add finance module tables

Revision ID: 6e6d292f08ce
Revises: 0c1abc082fb1
Create Date: 2026-09-13 00:25:25.796900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e6d292f08ce'
down_revision: Union[str, None] = '0c1abc082fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('venue', 'catering', 'logistics', 'publicity', 'technical', 'hospitality', 'administration', 'contingency', 'sponsorship_benefits', 'other', name='budgetcategory'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('spent_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('financial_year', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'approved', 'overspent', name='budgetstatus'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_items_category'), 'budget_items', ['category'], unique=False)
    op.create_index(op.f('ix_budget_items_id'), 'budget_items', ['id'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('bank_details', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('catering', 'printing', 'av_equipment', 'transport', 'accommodation', 'stationery', 'it_services', 'other', name='vendorcategory'), nullable=False),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('total_transactions', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'blacklisted', name='vendorstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_category'), 'vendors', ['category'], unique=False)
    op.create_index(op.f('ix_vendors_gstin'), 'vendors', ['gstin'], unique=False)
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.create_table('admin_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('official_correspondence', 'institutional_docs', 'committee_docs', 'certificates', 'conference_files', 'legal', 'financial', 'other', name='filecategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_reference_number', sa.String(length=100), nullable=True),
    sa.Column('file_date', sa.Date(), nullable=True),
    sa.Column('file_reference', sa.String(length=500), nullable=True),
    sa.Column('confidentiality', sa.Enum('public', 'internal', 'confidential', 'restricted', name='confidentialitylevel'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_files_category'), 'admin_files', ['category'], unique=False)
    op.create_index(op.f('ix_admin_files_file_date'), 'admin_files', ['file_date'], unique=False)
    op.create_index(op.f('ix_admin_files_file_reference_number'), 'admin_files', ['file_reference_number'], unique=False)
    op.create_index(op.f('ix_admin_files_id'), 'admin_files', ['id'], unique=False)
    op.create_table('bills_vouchers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_number', sa.String(length=100), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('vendor_gstin', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('bill_type', sa.Enum('invoice', 'receipt', 'voucher', 'cash_memo', 'credit_note', 'debit_note', name='billtype'), nullable=False),
    sa.Column('file_reference', sa.String(length=500), nullable=True),
    sa.Column('verification_status', sa.Enum('pending', 'verified', 'rejected', name='verificationstatus'), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_vouchers_bill_date'), 'bills_vouchers', ['bill_date'], unique=False)
    op.create_index(op.f('ix_bills_vouchers_bill_number'), 'bills_vouchers', ['bill_number'], unique=False)
    op.create_index(op.f('ix_bills_vouchers_id'), 'bills_vouchers', ['id'], unique=False)
    op.create_table('financial_reconciliation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reconciliation_type', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('difference', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('matched', 'mismatched', 'pending', name='reconciliationstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reconciled_by', sa.UUID(), nullable=True),
    sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciled_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_reconciliation_id'), 'financial_reconciliation', ['id'], unique=False)
    op.create_table('meeting_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('meeting_type', sa.Enum('finance_committee', 'coordination', 'review', 'audit', 'other', name='meetingtype'), nullable=False),
    sa.Column('meeting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('attendees', sa.JSON(), nullable=True),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('minutes', sa.Text(), nullable=True),
    sa.Column('decisions', sa.Text(), nullable=True),
    sa.Column('action_items', sa.Text(), nullable=True),
    sa.Column('file_reference', sa.String(length=500), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_records_id'), 'meeting_records', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_records_meeting_date'), 'meeting_records', ['meeting_date'], unique=False)
    op.create_index(op.f('ix_meeting_records_meeting_type'), 'meeting_records', ['meeting_type'], unique=False)
    op.create_table('procurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('actual_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('committee_requesting', sa.String(length=50), nullable=False),
    sa.Column('purchase_order_number', sa.String(length=100), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('expected_delivery', sa.Date(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('requested', 'approved', 'ordered', 'received', 'cancelled', name='procurementstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurements_committee_requesting'), 'procurements', ['committee_requesting'], unique=False)
    op.create_index(op.f('ix_procurements_id'), 'procurements', ['id'], unique=False)
    op.create_index(op.f('ix_procurements_purchase_order_number'), 'procurements', ['purchase_order_number'], unique=False)
    op.create_table('sponsorships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sponsor_name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('sponsorship_type', sa.Enum('cash', 'in_kind', 'both', name='sponsorshiptype'), nullable=False),
    sa.Column('cash_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('in_kind_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('in_kind_description', sa.Text(), nullable=True),
    sa.Column('benefits_offered', sa.Text(), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('agreement_date', sa.Date(), nullable=True),
    sa.Column('receipt_date', sa.Date(), nullable=True),
    sa.Column('receipt_number', sa.String(length=100), nullable=True),
    sa.Column('agreement_file', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('prospective', 'in_discussion', 'confirmed', 'received', 'declined', name='sponsorshipstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsorships_id'), 'sponsorships', ['id'], unique=False)
    op.create_index(op.f('ix_sponsorships_sponsor_name'), 'sponsorships', ['sponsor_name'], unique=False)
    op.create_table('expenditures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('category', sa.Enum('venue', 'catering', 'logistics', 'publicity', 'technical', 'hospitality', 'administration', 'contingency', 'sponsorship_benefits', 'other', name='budgetcategory'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('expenditure_date', sa.Date(), nullable=False),
    sa.Column('committee', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'bank_transfer', 'upi', 'cheque', 'card', name='paymentmethod'), nullable=False),
    sa.Column('paid_to', sa.String(length=255), nullable=False),
    sa.Column('paid_to_gstin', sa.String(length=20), nullable=True),
    sa.Column('bill_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'paid', 'rejected', name='expenditurestatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills_vouchers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenditures_category'), 'expenditures', ['category'], unique=False)
    op.create_index(op.f('ix_expenditures_committee'), 'expenditures', ['committee'], unique=False)
    op.create_index(op.f('ix_expenditures_expenditure_date'), 'expenditures', ['expenditure_date'], unique=False)
    op.create_index(op.f('ix_expenditures_id'), 'expenditures', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenditures_id'), table_name='expenditures')
    op.drop_index(op.f('ix_expenditures_expenditure_date'), table_name='expenditures')
    op.drop_index(op.f('ix_expenditures_committee'), table_name='expenditures')
    op.drop_index(op.f('ix_expenditures_category'), table_name='expenditures')
    op.drop_table('expenditures')
    op.drop_index(op.f('ix_sponsorships_sponsor_name'), table_name='sponsorships')
    op.drop_index(op.f('ix_sponsorships_id'), table_name='sponsorships')
    op.drop_table('sponsorships')
    op.drop_index(op.f('ix_procurements_purchase_order_number'), table_name='procurements')
    op.drop_index(op.f('ix_procurements_id'), table_name='procurements')
    op.drop_index(op.f('ix_procurements_committee_requesting'), table_name='procurements')
    op.drop_table('procurements')
    op.drop_index(op.f('ix_meeting_records_meeting_type'), table_name='meeting_records')
    op.drop_index(op.f('ix_meeting_records_meeting_date'), table_name='meeting_records')
    op.drop_index(op.f('ix_meeting_records_id'), table_name='meeting_records')
    op.drop_table('meeting_records')
    op.drop_index(op.f('ix_financial_reconciliation_id'), table_name='financial_reconciliation')
    op.drop_table('financial_reconciliation')
    op.drop_index(op.f('ix_bills_vouchers_id'), table_name='bills_vouchers')
    op.drop_index(op.f('ix_bills_vouchers_bill_number'), table_name='bills_vouchers')
    op.drop_index(op.f('ix_bills_vouchers_bill_date'), table_name='bills_vouchers')
    op.drop_table('bills_vouchers')
    op.drop_index(op.f('ix_admin_files_id'), table_name='admin_files')
    op.drop_index(op.f('ix_admin_files_file_reference_number'), table_name='admin_files')
    op.drop_index(op.f('ix_admin_files_file_date'), table_name='admin_files')
    op.drop_index(op.f('ix_admin_files_category'), table_name='admin_files')
    op.drop_table('admin_files')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_gstin'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_category'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_budget_items_id'), table_name='budget_items')
    op.drop_index(op.f('ix_budget_items_category'), table_name='budget_items')
    op.drop_table('budget_items')
    # ### end Alembic commands ###
