"""add simplified RBAC

Revision ID: 6ead7bb6a7b8
Revises: 024677c27b7b
Create Date: 2026-09-11 13:46:07.299802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ead7bb6a7b8'
down_revision: Union[str, None] = '024677c27b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('admin_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('specialized_domain', sa.String(length=100), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'used', 'expired', 'revoked', name='invitestatus'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_invites_email'), 'admin_invites', ['email'], unique=False)
    op.create_index(op.f('ix_admin_invites_token'), 'admin_invites', ['token'], unique=True)
    op.create_index('ix_invite_email', 'admin_invites', ['email'], unique=False)
    op.create_index('ix_invite_status', 'admin_invites', ['status'], unique=False)
    op.create_index('ix_invite_token', 'admin_invites', ['token'], unique=False)
    op.create_table('announcements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('target_audience', sa.Enum('all', 'presenters', 'unpaid', name='announcementtarget'), nullable=False),
    sa.Column('sent_by', sa.UUID(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_announcement_sent_at', 'announcements', ['sent_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_admin', 'audit_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_admin_id'), 'audit_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.drop_constraint('reviews_reviewer_id_fkey', 'reviews', type_='foreignkey')
    op.drop_table('reviewers')
    op.drop_table('volunteers')
    op.drop_table('attendance')
    op.drop_table('paper_authors')
    
    paperdomain = postgresql.ENUM('mining', 'renewable', 'environmental', name='paperdomain')
    paperdomain.create(op.get_bind(), checkfirst=True)
    
    reviewdecision = postgresql.ENUM('accepted', 'rejected', name='reviewdecision')
    reviewdecision.create(op.get_bind(), checkfirst=True)
    
    op.add_column('papers', sa.Column('domain', postgresql.ENUM('mining', 'renewable', 'environmental', name='paperdomain'), nullable=False, server_default='mining'))
    op.add_column('papers', sa.Column('assigned_reviewer_id', sa.UUID(), nullable=True))
    op.add_column('papers', sa.Column('review_status', postgresql.ENUM('submitted', 'under_review', 'accepted', 'rejected', name='paperstatus'), nullable=False, server_default='submitted'))
    op.add_column('papers', sa.Column('decision', sa.String(length=50), nullable=True))
    op.add_column('papers', sa.Column('comments_for_authors', sa.Text(), nullable=True))
    op.add_column('papers', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('papers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_paper_domain', 'papers', ['domain'], unique=False)
    op.create_index('ix_paper_reviewer', 'papers', ['assigned_reviewer_id'], unique=False)
    op.create_index('ix_paper_status', 'papers', ['review_status'], unique=False)
    op.create_index(op.f('ix_papers_assigned_reviewer_id'), 'papers', ['assigned_reviewer_id'], unique=False)
    op.create_index(op.f('ix_papers_id'), 'papers', ['id'], unique=False)
    op.create_index(op.f('ix_papers_registration_id'), 'papers', ['registration_id'], unique=False)
    op.create_index(op.f('ix_papers_review_status'), 'papers', ['review_status'], unique=False)
    op.create_foreign_key(None, 'papers', 'users', ['assigned_reviewer_id'], ['id'])
    op.drop_column('papers', 'track')
    op.drop_column('papers', 'status')
    op.add_column('reviews', sa.Column('decision', postgresql.ENUM('accepted', 'rejected', name='reviewdecision'), nullable=False, server_default='accepted'))
    op.add_column('reviews', sa.Column('comments_for_authors', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('confidential_comments', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('reviews', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_review_paper', 'reviews', ['paper_id'], unique=False)
    op.create_index('ix_review_reviewer', 'reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_reviews_paper_id'), 'reviews', ['paper_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    op.create_foreign_key(None, 'reviews', 'users', ['reviewer_id'], ['id'])
    op.drop_column('reviews', 'submitted')
    op.drop_column('reviews', 'scores_json')
    op.drop_column('reviews', 'submitted_at')
    op.drop_column('reviews', 'recommendation')
    op.drop_column('reviews', 'assigned_at')
    op.drop_column('reviews', 'comments')
    op.add_column('users', sa.Column('specialized_domain', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Integer(), nullable=False, server_default='1'))
    op.alter_column('users', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'state',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index('ix_user_domain', 'users', ['specialized_domain'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index('ix_user_domain', table_name='users')
    op.alter_column('users', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'state',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'specialized_domain')
    op.add_column('reviews', sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('recommendation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('scores_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('submitted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key('reviews_reviewer_id_fkey', 'reviews', 'reviewers', ['reviewer_id'], ['id'])
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_paper_id'), table_name='reviews')
    op.drop_index('ix_review_reviewer', table_name='reviews')
    op.drop_index('ix_review_paper', table_name='reviews')
    op.drop_column('reviews', 'updated_at')
    op.drop_column('reviews', 'created_at')
    op.drop_column('reviews', 'confidential_comments')
    op.drop_column('reviews', 'comments_for_authors')
    op.drop_column('reviews', 'decision')
    op.add_column('papers', sa.Column('status', postgresql.ENUM('submitted', 'under_review', 'accepted', 'rejected', 'revision_needed', name='paperstatus'), autoincrement=False, nullable=True))
    op.add_column('papers', sa.Column('track', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'papers', type_='foreignkey')
    op.drop_index(op.f('ix_papers_review_status'), table_name='papers')
    op.drop_index(op.f('ix_papers_registration_id'), table_name='papers')
    op.drop_index(op.f('ix_papers_id'), table_name='papers')
    op.drop_index(op.f('ix_papers_assigned_reviewer_id'), table_name='papers')
    op.drop_index('ix_paper_status', table_name='papers')
    op.drop_index('ix_paper_reviewer', table_name='papers')
    op.drop_index('ix_paper_domain', table_name='papers')
    op.alter_column('papers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('papers', 'reviewed_at')
    op.drop_column('papers', 'comments_for_authors')
    op.drop_column('papers', 'decision')
    op.drop_column('papers', 'review_status')
    op.drop_column('papers', 'assigned_reviewer_id')
    op.drop_column('papers', 'domain')
    op.create_table('paper_authors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('paper_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_corresponding', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name='paper_authors_paper_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='paper_authors_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='paper_authors_pkey')
    )
    op.create_table('attendance',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('registration_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scanned_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('scanned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], name='attendance_registration_id_fkey'),
    sa.ForeignKeyConstraint(['scanned_by'], ['users.id'], name='attendance_scanned_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='attendance_pkey')
    )
    op.create_table('volunteers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('shift', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('assigned_duty', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='volunteers_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='volunteers_pkey')
    )
    op.create_table('reviewers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('track', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expertise', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='reviewers_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reviewers_pkey')
    )
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index('ix_audit_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_admin_id'), table_name='audit_logs')
    op.drop_index('ix_audit_admin', table_name='audit_logs')
    op.drop_index('ix_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_announcement_sent_at', table_name='announcements')
    op.drop_table('announcements')
    op.drop_index('ix_invite_token', table_name='admin_invites')
    op.drop_index('ix_invite_status', table_name='admin_invites')
    op.drop_index('ix_invite_email', table_name='admin_invites')
    op.drop_index(op.f('ix_admin_invites_token'), table_name='admin_invites')
    op.drop_index(op.f('ix_admin_invites_email'), table_name='admin_invites')
    op.drop_table('admin_invites')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
