"""make admin_id nullable in audit log

Revision ID: 718d393f0f50
Revises: bfe851e40d6e
Create Date: 2026-09-11 21:02:39.581097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '718d393f0f50'
down_revision: Union[str, None] = 'bfe851e40d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'admin_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'admin_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
