"""add profile fields and meal claims

Revision ID: 93fa329c9405
Revises: 54ebe2e768d2
Create Date: 2026-09-10 17:17:35.807152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93fa329c9405'
down_revision: Union[str, None] = '54ebe2e768d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'dinner', name='mealtype'), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=False),
    sa.Column('scanned_by_volunteer_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.ForeignKeyConstraint(['scanned_by_volunteer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_id', 'meal_type', name='uq_registration_meal')
    )
    op.create_index('ix_meal_claim_reg', 'meal_claims', ['registration_id', 'meal_type'], unique=False)
    op.create_index(op.f('ix_meal_claims_registration_id'), 'meal_claims', ['registration_id'], unique=False)
    op.alter_column('registrations', 'payment_status',
               existing_type=postgresql.ENUM('pending', 'paid', 'failed', name='paymentstatus'),
               nullable=False)
    op.drop_constraint('registrations_qr_hash_key', 'registrations', type_='unique')
    op.create_index(op.f('ix_registrations_id'), 'registrations', ['id'], unique=False)
    op.create_index(op.f('ix_registrations_payment_status'), 'registrations', ['payment_status'], unique=False)
    op.create_index(op.f('ix_registrations_qr_hash'), 'registrations', ['qr_hash'], unique=True)
    op.create_index(op.f('ix_registrations_user_id'), 'registrations', ['user_id'], unique=False)
    op.drop_column('registrations', 'co_authors')
    op.drop_column('registrations', 'student_class')
    op.drop_column('registrations', 'paper_title')
    op.drop_column('registrations', 'experience')
    op.drop_column('registrations', 'sub_category')
    op.drop_column('registrations', 'city')
    op.drop_column('registrations', 'state')
    op.drop_column('registrations', 'organization')
    op.drop_column('registrations', 'graduation_year')
    op.drop_column('registrations', 'created_at')
    op.drop_column('registrations', 'designation')
    op.drop_column('registrations', 'accompanying_count')
    op.drop_column('registrations', 'education_level')
    op.drop_column('registrations', 'field_of_study')
    op.add_column('users', sa.Column('category', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('state', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('education_level', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('student_class', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('field_of_study', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('graduation_year', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('organization', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('designation', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('experience', sa.Integer(), nullable=True))
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index('ix_user_role', 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('ix_user_role', table_name='users')
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'experience')
    op.drop_column('users', 'designation')
    op.drop_column('users', 'organization')
    op.drop_column('users', 'graduation_year')
    op.drop_column('users', 'field_of_study')
    op.drop_column('users', 'student_class')
    op.drop_column('users', 'education_level')
    op.drop_column('users', 'city')
    op.drop_column('users', 'state')
    op.drop_column('users', 'category')
    op.add_column('registrations', sa.Column('field_of_study', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('registrations', sa.Column('education_level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('registrations', sa.Column('accompanying_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('registrations', sa.Column('designation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('registrations', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('registrations', sa.Column('graduation_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('registrations', sa.Column('organization', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('registrations', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('registrations', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('registrations', sa.Column('sub_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('registrations', sa.Column('experience', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('registrations', sa.Column('paper_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('registrations', sa.Column('student_class', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('registrations', sa.Column('co_authors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_registrations_user_id'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_qr_hash'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_payment_status'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_id'), table_name='registrations')
    op.create_unique_constraint('registrations_qr_hash_key', 'registrations', ['qr_hash'])
    op.alter_column('registrations', 'payment_status',
               existing_type=postgresql.ENUM('pending', 'paid', 'failed', name='paymentstatus'),
               nullable=True)
    op.drop_index(op.f('ix_meal_claims_registration_id'), table_name='meal_claims')
    op.drop_index('ix_meal_claim_reg', table_name='meal_claims')
    op.drop_table('meal_claims')
    # ### end Alembic commands ###
