"""add volunteer invite codes and staff attendance

Revision ID: 97132cf85d3e
Revises: 4a37c8fda5f7
Create Date: 2026-09-12 13:58:53.625484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97132cf85d3e'
down_revision: Union[str, None] = '4a37c8fda5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
