"""add media module tables

Revision ID: aedceb6f12ac
Revises: 6e6d292f08ce
Create Date: 2026-09-13 01:48:35.381950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aedceb6f12ac'
down_revision: Union[str, None] = '6e6d292f08ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_archive_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.Enum('photo', 'video', name='mediatype'), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=True),
    sa.Column('date_captured', sa.Date(), nullable=True),
    sa.Column('file_reference', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_archive_items_id'), 'media_archive_items', ['id'], unique=False)
    op.create_table('press_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('target_media', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('draft', 'issued', name='pressnotestatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_press_notes_id'), 'press_notes', ['id'], unique=False)
    op.create_table('publicity_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', name='publicitytaskstatus'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publicity_tasks_id'), 'publicity_tasks', ['id'], unique=False)
    op.create_table('social_media_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('twitter', 'instagram', 'linkedin', 'facebook', 'youtube', name='socialplatform'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'published', name='socialpoststatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_media_posts_id'), 'social_media_posts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_media_posts_id'), table_name='social_media_posts')
    op.drop_table('social_media_posts')
    op.drop_index(op.f('ix_publicity_tasks_id'), table_name='publicity_tasks')
    op.drop_table('publicity_tasks')
    op.drop_index(op.f('ix_press_notes_id'), table_name='press_notes')
    op.drop_table('press_notes')
    op.drop_index(op.f('ix_media_archive_items_id'), table_name='media_archive_items')
    op.drop_table('media_archive_items')
    # ### end Alembic commands ###
