"""add settings table

Revision ID: bfe851e40d6e
Revises: 19a8d4be6647
Create Date: 2026-09-11 20:38:21.706529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe851e40d6e'
down_revision: Union[str, None] = '19a8d4be6647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conference_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conference_name', sa.String(length=255), nullable=True),
    sa.Column('conference_dates', sa.String(length=100), nullable=True),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('student_fee', sa.Integer(), nullable=True),
    sa.Column('professional_fee', sa.Integer(), nullable=True),
    sa.Column('accompanying_fee', sa.Integer(), nullable=True),
    sa.Column('paper_submission_deadline', sa.DateTime(), nullable=True),
    sa.Column('registration_deadline', sa.DateTime(), nullable=True),
    sa.Column('meal_timings', sa.JSON(), nullable=True),
    sa.Column('domains', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conference_settings')
    # ### end Alembic commands ###
