"""add user_id to meal_claims

Revision ID: c5c8db5c43d8
Revises: 99eaf6368565
Create Date: 2026-09-12 15:16:01.929944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5c8db5c43d8'
down_revision: Union[str, None] = '99eaf6368565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_claims', sa.Column('user_id', sa.UUID(), nullable=True))
    op.alter_column('meal_claims', 'registration_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_meal_claims_user_id'), 'meal_claims', ['user_id'], unique=False)
    op.drop_constraint('meal_claims_registration_id_fkey', 'meal_claims', type_='foreignkey')
    op.create_foreign_key(None, 'meal_claims', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'meal_claims', 'registrations', ['registration_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meal_claims', type_='foreignkey')
    op.drop_constraint(None, 'meal_claims', type_='foreignkey')
    op.create_foreign_key('meal_claims_registration_id_fkey', 'meal_claims', 'registrations', ['registration_id'], ['id'])
    op.drop_index(op.f('ix_meal_claims_user_id'), table_name='meal_claims')
    op.alter_column('meal_claims', 'registration_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('meal_claims', 'user_id')
    # ### end Alembic commands ###
